// <auto-generated />
using System;
using Chatbot_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Chatbot_API.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220813173540_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Chatbot_API.Entities.CHAT_HISTORIE", b =>
                {
                    b.Property<int>("CHAT_HISTORIE_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CHAT_HISTORIE_ID"));

                    b.Property<int>("CREATED_BY")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CREATED_DATETIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IS_COMPLTE")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UPDATE_DATETIME")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("USER_ID")
                        .HasColumnType("integer");

                    b.Property<string>("USER_TYPE")
                        .HasColumnType("text");

                    b.HasKey("CHAT_HISTORIE_ID");

                    b.ToTable("CHAT_HISTORIE");
                });

            modelBuilder.Entity("Chatbot_API.Entities.CHAT_HISTORIE_DETAIL", b =>
                {
                    b.Property<int>("CHAT_HISTORIE_DETAIL_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CHAT_HISTORIE_DETAIL_ID"));

                    b.Property<int?>("BUTTON_ID")
                        .HasColumnType("integer");

                    b.Property<int>("CHAT_HISTORIE_ID")
                        .HasColumnType("integer");

                    b.Property<int>("CREATED_BY")
                        .HasColumnType("integer");

                    b.Property<bool>("IS_TOPIC")
                        .HasColumnType("boolean");

                    b.Property<string>("MESSAGES")
                        .HasColumnType("text");

                    b.Property<DateTime>("TIME_STAMP")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TOPICS")
                        .HasColumnType("text");

                    b.Property<string>("USER_TYPE")
                        .HasColumnType("text");

                    b.HasKey("CHAT_HISTORIE_DETAIL_ID");

                    b.HasIndex("CHAT_HISTORIE_ID");

                    b.ToTable("CHAT_HISTORIE_DETAIL");
                });

            modelBuilder.Entity("Chatbot_API.Entities.CHAT_HISTORIE_DETAIL", b =>
                {
                    b.HasOne("Chatbot_API.Entities.CHAT_HISTORIE", "CHAT_HISTORIE")
                        .WithMany("CHAT_HISTORIE_DETAILS")
                        .HasForeignKey("CHAT_HISTORIE_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CHAT_HISTORIE");
                });

            modelBuilder.Entity("Chatbot_API.Entities.CHAT_HISTORIE", b =>
                {
                    b.Navigation("CHAT_HISTORIE_DETAILS");
                });
#pragma warning restore 612, 618
        }
    }
}
